### ISSUE TITLE
Commented out IAM Role ARN's

### ISSUE THREAD

**Issue by airmonitor** [aws-samples/iam-policy-tester-pipeline#3]
Hey.

Thx for sharing.
I'm wondering what was the reason for leaving commented out Role ARN's?

https://github.com/aws-samples/iam-policy-tester-pipeline/blob/master/Pipeline/ToolsAcct/code-pipeline.yaml

`#RoleArn: !Sub arn:aws:iam::${TestAccount}:role/cloudformationdeployer-role`

**Comment by ConnorKirk** [comment]
Hi airmonitor,

This was my mistake. Thank you for pointing highlighting it. I will tidy it up. 🙂

**Comment by ConnorKirk** [comment]
This is now fixed in #5 . Thanks airmonitor for pointing it out.
