### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by pputnik** [aws-samples/iam-policy-tester-pipeline#4]
Hi,
/single-click-cross-account-pipeline.sh:  there's nothing in doc what ToolsAccount stands for/needed. In the blog article https://aws.amazon.com/blogs/devops/unit-testing-iam-policies-across-multiple-accounts/ there's no mention as well.

**Comment by waymousa** [comment]
Thank you for your feedback.  I have updated the README.md with a link to the cross-account CI/CD delivery blog post that we refer to in this repo.  This article describes the ToolsAccount as "A central location for all the tools related to the organization, including continuous delivery/deployment services such as AWS CodePipeline and AWS CodeBuild. Developers have limited/read-only access in this account. The Operations team has more control." Please let us know if this answers your question.
